apiVersion: v1
kind: ConfigMap
metadata:
  namespace: redis
  labels:
    name: redis
  name: redis-cluster-conf
# maxmemory 设置为 limit.memory 80%
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    maxmemory 966367641
    maxmemory-policy noeviction 
    appendonly yes
    appendfsync always 
    tcp-keepalive 60
    protected-mode no
    requirepass xxxxx
